import Tkinter as tk
from guidoc import tk_layout

basic_packed = '''
myFrame(Frame)
  myButton(Button | text='Button text')
  myLabel(Label | text='Label text')
'''

basic_pack_horiz = '''
myFrame(Frame)
  myButton(Button | text='Button text') <pack | side='left'>
  myLabel(Label | text='Label text', bg='red') <pack | side='left'>
'''

basic_grid = '''
myFrame(Frame)
  myButton(Button | text='Button text') <grid | row=0, column=0>
  myLabel(Label | text='Label text', bg='red') <grid | row=1, column=1>
'''


gridded = '''

frameA(Frame | relief='raised', bd=3, bg='red') < pack | side='left' >
  lblA(Label | text='lblA') < grid | padx=2, pady=2 >
  lblB(Label | text='lblB')
  lblC(Label | text='lblC')
frameB(Frame | relief='raised', bd=3, bg='green') < pack | side='right' >
  lblX(Label | text='lblX') < grid | padx=2, pady=2 >
  lblY(Label | text='lblY')
  lblZ(Label | text='lblZ')

[grid frameA]    # Grid table format:

+------+------+
| lblA |      |
+------+ lblC |
| lblB |      |
+------+------+

[grid frameB]    # Simple table format:

# lblZ spans two columns
==== ====
lblX lblY
  lblZ
---------
==== ====
'''


menu = '''
myFrame(Frame)
  myButton(Button | text='Button text')
  myLabel(Label | text='Label text')

[menu]

&File
  &Open  command=None
  &Save  command=None
&Settings
  [] 'Check 1'  variable=self.Check1Val
  [] 'Check 2'  variable=self.Check2Val
  ----
  * 'Radio 1'   variable=self.RadioVal, value='1'
  * 'Radio 2'   variable=self.RadioVal, value='2'
  * 'Radio 3'   variable=self.RadioVal, value='3'
&Help
  &About  command=None
'''
  

@tk_layout(menu)
class MyApp(tk.Frame):
  def __init__(self, parent):
    tk.Frame.__init__(self, parent)
    self.pack(fill='both', expand=1)
    
    self.Check1Val = tk.IntVar()
    self.Check2Val = tk.IntVar()
    self.Check2Val.set(1)

    self.RadioVal = tk.StringVar()
    self.RadioVal.set('1')  # Initialize the value
    
    self._build_widgets()  # This method is generated by tk_layout()
    
    self.menubar.config(tearoff=1)

root = tk.Tk()
app = MyApp(root)
root.mainloop()
