import Tkinter as tk
from guidoc import tk_layout

@tk_layout(r'''
btnA(Button | text='Button A')
btnB(Button | text='Button B')
btnC(Button | text='Button C\n(spanning two columns)')
frmX(Frame)
  lbl1(Label | text='Widgets default', bg='red')
  lbl2(Label | text='to using the pack', bg='white')
  lbl3(Label | text='geometry manager', bg='blue', fg='white')

[grid]    # Grid layout for the top level widgets

+-----+------+------+
|btnA | btnB |      |
+-----+------+ frmX |
|    btnC    |      |
+------------+------+
''')
class MyApp(tk.Frame):
  def __init__(self, parent):
    tk.Frame.__init__(self, parent)
    self.pack(fill='both', expand=1)
    self._build_widgets()  # This method is generated by tk_layout()

root = tk.Tk()
app = MyApp(root)
root.mainloop()
